# Generated by Django 3.2.6 on 2021-08-23 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='bio',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
